enum {
    DKEY_SELECT = 0,
    DKEY_L3,
    DKEY_R3,
    DKEY_START,
    DKEY_UP,
    DKEY_RIGHT,
    DKEY_DOWN,
    DKEY_LEFT,
    DKEY_L2,
    DKEY_R2,
    DKEY_L1,
    DKEY_R1,
    DKEY_TRIANGLE,
    DKEY_CIRCLE,
    DKEY_CROSS,
    DKEY_SQUARE,
};

#define PSE_PAD_TYPE_NONE			0
#define PSE_PAD_TYPE_STANDARD		4